version: "2"
services:
  web:
    build: .
    tty: true
    stdin_open: true
    ports:
      - "8080:8080"
    env_file:
      - ./src/config/.env
    depends_on:
      - db
  
  db:
    image: postgres:12.3
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
